image: Visual Studio 2019
version: '1.0.{build}'
configuration:
- Debug
- Release
platform: Any CPU
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./src/Reacher.csproj --verbosity m
build_script:
- dotnet build "./src/Reacher.csproj" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
install:
  # Cake build is targeting `.NET Core` `3.1.0`, so we can safely install the latest supported `SDK`
  # The `SDK` is required to restore, build, publish... a `.NET Core` application
  # https://www.microsoft.com/net/download/windows
  - ps: .\build\dotnet-install.ps1
  - ps: dotnet tool install --global Cake.Tool --version 0.35.0
