version: '1.0.{build}'
configuration:
- Debug
- Release
platform: Any CPU
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./src/Reacher.csproj --verbosity m
build_script:
- dotnet build "./src/Reacher.csproj" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
